package com.vnaskos.biodictionary;

import com.vnaskos.biodictionary.translator.Translate;
import javax.swing.DefaultListModel;

/**
 *
 * @author Vasilis Naskos
 */
public class Help extends javax.swing.JFrame {    
    
    Translate tr;
    DefaultListModel model = new DefaultListModel();
    String[] helpArray = new String[12];
    
    public Help(Translate tr) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.tr = tr;
        this.setTitle(tr.getString("biodictionary.Help.windowTitle"));
        okButton.setText(tr.getString("biodictionary.Help.okButton"));
        initModel();
        initHelpArray();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        contentTextArea = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        topicList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BioDictionary Help");
        setMinimumSize(new java.awt.Dimension(535, 355));

        contentTextArea.setEditable(false);
        contentTextArea.setColumns(20);
        contentTextArea.setLineWrap(true);
        contentTextArea.setRows(5);
        contentTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(contentTextArea);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        topicList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                topicListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(topicList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addGap(7, 7, 7))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void topicListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_topicListValueChanged
        showTopic();
    }//GEN-LAST:event_topicListValueChanged
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contentTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okButton;
    private javax.swing.JList topicList;
    // End of variables declaration//GEN-END:variables

    public final void initModel() {
        model.addElement(tr.getString("biodictionary.Help.topic1"));
        model.addElement(tr.getString("biodictionary.Help.topic2"));
        model.addElement(tr.getString("biodictionary.Help.topic3"));
        model.addElement(tr.getString("biodictionary.Help.topic4"));
        model.addElement(tr.getString("biodictionary.Help.topic5"));
        model.addElement(tr.getString("biodictionary.Help.topic6"));
        model.addElement(tr.getString("biodictionary.Help.topic7"));
        model.addElement(tr.getString("biodictionary.Help.topic8"));
        model.addElement(tr.getString("biodictionary.Help.topic9"));
        model.addElement(tr.getString("biodictionary.Help.topic10"));
        model.addElement(tr.getString("biodictionary.Help.topic11"));
        model.addElement(tr.getString("biodictionary.Help.topic12"));
        topicList.setModel(model);
    }

    public final void initHelpArray() {
        helpArray[0] = tr.getString("biodictionary.Help.topic1.text");
        helpArray[1] = tr.getString("biodictionary.Help.topic2.text");
        helpArray[2] = tr.getString("biodictionary.Help.topic3.text");
        helpArray[3] = tr.getString("biodictionary.Help.topic4.text");
        helpArray[4] = tr.getString("biodictionary.Help.topic5.text");
        helpArray[5] = tr.getString("biodictionary.Help.topic6.text");
        helpArray[6] = tr.getString("biodictionary.Help.topic7.text");
        helpArray[7] = tr.getString("biodictionary.Help.topic8.text");
        helpArray[8] = tr.getString("biodictionary.Help.topic9.text");
        helpArray[9] = tr.getString("biodictionary.Help.topic10.text");
        helpArray[10] = tr.getString("biodictionary.Help.topic11.text");
        helpArray[11] = tr.getString("biodictionary.Help.topic12.text");

    }

    public void showTopic() {
        int topicIndex = topicList.getSelectedIndex();
        contentTextArea.setText(helpArray[topicIndex]);
    }
}
