package com.vnaskos.biodictionary;

import com.vnaskos.biodictionary.translator.LanguageItem;
import com.vnaskos.biodictionary.translator.Languages;
import com.vnaskos.biodictionary.translator.Translate;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Vasilis Naskos
 */
public class ProgramPreferences extends javax.swing.JFrame {

    Translate tr;
    DefaultComboBoxModel model;
    
    public ProgramPreferences(Translate tr) {
        initComponents();
        this.tr = tr;
        this.setTitle(tr.getString("biodictionary.ProgramPreferences.windowTitle"));
        this.setLocationRelativeTo(null);
        model = new DefaultComboBoxModel();
        model.addElement(new LanguageItem("English", Languages.EN));
        model.addElement(new LanguageItem("Ελληνικά", Languages.GR));
        model.addElement(new LanguageItem("Español", Languages.ES));
        model.addElement(new LanguageItem("Türkçe", Languages.TK));
        languageComboBox.setModel(model);
        
        setComboBoxSelection();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languageLabel = new javax.swing.JLabel();
        languageComboBox = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BioDictionary Preferences");
        setAlwaysOnTop(true);
        setResizable(false);

        languageLabel.setText("Language:");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(languageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(languageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        LanguageItem lang = (LanguageItem) languageComboBox.getSelectedItem();
        tr.setLanguage(lang.getLang());
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox languageComboBox;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    public void updateLanguage() {
        languageLabel.setText(tr.getString("biodictionary.ProgramPreferences.languageLabel"));
        okButton.setText(tr.getString("biodictionary.ProgramPreferences.okButton"));
        cancelButton.setText(tr.getString("biodictionary.ProgramPreferences.cancelButton"));
        setComboBoxSelection();
    }

    private void setComboBoxSelection() {
        Languages lang = tr.getLanguage();
        int langIndex = 0;

        for (int i = 0; i < model.getSize(); i++) {
            LanguageItem item = (LanguageItem) model.getElementAt(i);
            if (item.getLang() == lang) {
                langIndex = i;
                break;
            }
        }

        languageComboBox.setSelectedIndex(langIndex);
    }
}
